services:
  mysql:
    image: mysql:8.0.32
    container_name: ai_interviewer_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - ai_interviewer_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai_interviewer_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      PORT: 8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - ai_interviewer_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai_interviewer_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ai_interviewer_network

volumes:
  mysql_data:

networks:
  ai_interviewer_network:
    driver: bridge
